(lang dune 3.23)
;; The test suite is its own Dune project so that it can use features of
;; recent Dune versions (expected-output tests for Rocq) without raising the
;; Dune version required to build Camltac itself.
(using rocq 0.12)

(generate_opam_files true)

(authors "Dario Halilovic")
(maintainers "Dario Halilovic")
(license LGPL-2.1-only)

(homepage "https://github.com/epfl-systemf/camltac")
(source
 (github epfl-systemf/camltac))
(bug_reports "https://github.com/epfl-systemf/camltac/issues")

(package
 (name camltac-tests)
 (synopsis "Camltac's test suite")
 (depends
   camltac
   rocq-stdlib))
