(library
 (name api)
 (public_name camltac.plugin.api)
 (synopsis "Stable APIs for interacting with Rocq")
 (libraries
   mltac2
   rocq-runtime.vernac
   rocq-runtime.plugins.ltac
   rocq-runtime.plugins.ltac2
   rocq-runtime.tactics)
 (preprocess (pps ppx_optcomp -- -cookie "ppx_optcomp.env=env ~rocq:(Defined (%{rocq:version.major}, %{rocq:version.minor}))")))
