(library
 (name camltac_plugin)
 (public_name camltac.plugin)
 (synopsis "OCaml as a Tactic Language")
 (libraries
   dynlink
   camltac.plugin.runtime
   camltac.plugin.api
   camltac-directives
   rocq-runtime.plugins.ltac
   rocq-runtime.plugins.ltac2
   findlib
   findlib.dynload
   ppx_rocq.runtime)
 (preprocess (pps ppx_optcomp -- -cookie "ppx_optcomp.env=env ~rocq:(Defined (%{coq:version.major}, %{coq:version.minor}))")))

(coq.pp
 (modules grammar))
