name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ ubuntu-latest ]
        rocq_version: [ "dev" ]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Camltac on Rocq ${{ matrix.rocq_version }}
        uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'camltac.opam'
          # Add camltac-directives to list of dependencies
          install: |
            startGroup "Install dependencies"
              sudo apt-get update -y -q
              opam pin add -n -y -k path camltac-directives $WORKDIR
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y
              opam install --confirm-level=unsafe-yes -j 2 $PACKAGE --deps-only
            endGroup
          coq_version: ${{ matrix.rocq_version }}